# Generated by Django 5.2.8 on 2025-11-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional longer description.')),
                ('is_done', models.BooleanField(default=False, help_text='Marks whether the task is completed.')),
                ('due_date', models.DateField(blank=True, help_text='Optional due date for the task.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated.')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['is_done', 'due_date', '-created_at'],
            },
        ),
    ]
