# Generated by Django 5.2.8 on 2025-11-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', 'position', models.OrderBy(models.F('due_date'), nulls_last=True), '-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0, help_text='Position for manual ordering of tasks.'),
        ),
    ]
